---
- name: install and start apache
  hosts: web
  become: yes

  tasks:
    - name: httpd package is present
      yum:
       name: httpd
       state: absent

    - name: Remove file (delete file)
      file:
        path: /var/www/html/
        state: absent
